[book]
authors = ["David Koloski"]
language = "en"
multilingual = false
src = "book_src"
title = "rkyv"

[output.html]
cname = "rkyv.org"
edit-url-template = "https://github.com/rkyv/rkyv/edit/master/{path}"
